### ISSUE TITLE
Check vehicle state without waking vehicle

### ISSUE THREAD

**Issue by apgodshall** [zmsp/python-my-tesla#1]
Problem: calling .vehicle_state() or other .vehicle_xxxx() wakes vehicle.

Solution: call .vehicles() first, and call .vehicle_state() or other .vehicle_xxxx() only if state is not 'asleep'

This should be documented in the README

**Comment by zmsp** [comment]
@apgodshall thanks so much for the issues/bug report. I was pleasantly surprised to see people were using it. Will work on implementing as soon as I get some free times.

**Comment by gilesgamon** [comment]
Further to @apgodshall's comment, my brief poke suggested vehicles['state'] can also report online, unknown & offline. I think @apgodshall's suggestion is good but suspect you'd need to note that power=0 and leave the car alone or it will never sleep - so the logic is good but needs refining

**Comment by apgodshall** [comment]
My tests show that querying the list of cars and inspecting that for state "asleep" does not wake the car.  2018 Tesla Model 3 LR.  Querying beyond that will probably wake it.

**Comment by apgodshall** [comment]
Thanks, zmsp!
