### ISSUE TITLE
trunk_open not working

### ISSUE THREAD

**Issue by ncliang** [zmsp/python-my-tesla#4]
https://github.com/zmsp/python-my-tesla/blob/bf3ceeae17a0f4b878debb97cbeb3a8b276d3d59/myTesla.py#L293

The POST will not hit the correct endpoint documented in https://tesla-api.timdorr.com/vehicle/commands/trunk#post-api-1-vehicles-id-command-actuate_trunk

This change fixes it:
```
-        return self.post_command("trunk_open", data=data)
+        return self.post_command("trunk_open",
+                                 command_url="/vehicles/{vehicle_id}/command/actuate_trunk",
+                                 data=data)
```

**Comment by zmsp** [comment]
thanks for the report. Will look.
